2024-01-15 20:50:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f454346f010>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-15 20:50:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f454346e9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-15 20:50:40 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f454346dcc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-15 20:50:45 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4540aac550>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-15 20:50:50 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f454346ed40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-15 20:50:55 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f454346f1f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-15 20:51:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f454346fa90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-15 20:51:05 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4540aac370>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-15 20:51:10 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4540aacdc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-15 20:51:15 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f454346dff0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-15 20:51:20 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f454346f400>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-15 20:51:25 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f454346e3b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-15 20:51:30 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4540aacd00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-15 20:51:35 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='127.0.0.1', port=20001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4540aac190>: Failed to establish a new connection: [Errno 111] Connection refused'))
